// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {message} from '../models';

export function LogIn(arg1:string):Promise<boolean>;

export function OpenConnection(arg1:message.Input):Promise<void>;

export function ReceiveInput():Promise<void>;

export function SendInput(arg1:string):Promise<void>;
