// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LogIn(arg1) {
  return window['go']['main']['App']['LogIn'](arg1);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function ReceiveInput() {
  return window['go']['main']['App']['ReceiveInput']();
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}
